# Generated by Django 3.1.1 on 2020-10-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingFormModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
