# Generated by Django 3.1.1 on 2020-10-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingformmodel',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
