# Generated by Django 3.1.1 on 2020-10-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201005_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingformmodel',
            name='message',
            field=models.CharField(default='OK', max_length=200),
        ),
    ]
