# Generated by Django 3.1.1 on 2020-10-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201005_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingformmodel',
            name='mobile',
            field=models.PositiveBigIntegerField(),
        ),
    ]
